# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\czari\Desktop\DocuApp.ver3\DocuApp_ver4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1009)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setGeometry(QtCore.QRect(0, 0, 1921, 1051))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 67, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 56, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 30, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 67, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 56, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 30, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 67, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 56, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 30, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 22, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 45, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.main_body.setPalette(palette)
        self.main_body.setMouseTracking(True)
        self.main_body.setAutoFillBackground(False)
        self.main_body.setStyleSheet("QFrame#main_body {\n"
"background: #1a1a1e;\n"
"}\n"
"\n"
"QFrame#headerr {\n"
"background: #121214;\n"
"}\n"
"\n"
"\n"
"QFrame#footer {\n"
"background: #121214;\n"
"}\n"
"\n"
"QFrame#selectionframe {\n"
"background: #2c2c30;\n"
"border: 1px solid #7a7a81;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QFrame#available_data_frame {\n"
"background: #2c2c30;\n"
"border: 1px solid #7a7a81;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QFrame#generate_frame {\n"
"background: #2c2c30;\n"
"border: 1px solid #7a7a81;\n"
"border-radius: 10px\n"
"}\n"
"QPushButton {\n"
"background: #0085ca;\n"
"font-size: 10pt;\n"
"color:white;\n"
"border-radius: 10px\n"
"\n"
"}\n"
"\n"
"QPushButtonn:hover {\n"
"    background:rgb(60, 100, 159);\n"
"font-size: 10pt;\n"
"border-radius: 10px\n"
"\n"
"}")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.footer = QtWidgets.QFrame(self.main_body)
        self.footer.setGeometry(QtCore.QRect(0, 980, 1921, 71))
        self.footer.setStyleSheet("")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.power_integrations_logo = QtWidgets.QLabel(self.footer)
        self.power_integrations_logo.setGeometry(QtCore.QRect(10, 20, 131, 41))
        self.power_integrations_logo.setText("")
        self.power_integrations_logo.setPixmap(QtGui.QPixmap(":/icons/resources/icons/POWI_BIG.D-8e645f4d.png"))
        self.power_integrations_logo.setScaledContents(True)
        self.power_integrations_logo.setObjectName("power_integrations_logo")
        self.waveforms_text_2 = QtWidgets.QLabel(self.footer)
        self.waveforms_text_2.setGeometry(QtCore.QRect(1850, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.waveforms_text_2.setFont(font)
        self.waveforms_text_2.setStyleSheet("color: rgb(112, 112, 112);")
        self.waveforms_text_2.setObjectName("waveforms_text_2")
        self.waveforms_text_3 = QtWidgets.QLabel(self.footer)
        self.waveforms_text_3.setGeometry(QtCore.QRect(1860, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.waveforms_text_3.setFont(font)
        self.waveforms_text_3.setStyleSheet("color: rgb(112, 112, 112);")
        self.waveforms_text_3.setObjectName("waveforms_text_3")
        self.generate_frame = QtWidgets.QFrame(self.main_body)
        self.generate_frame.setGeometry(QtCore.QRect(1280, 130, 611, 841))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.generate_frame.setPalette(palette)
        self.generate_frame.setAutoFillBackground(False)
        self.generate_frame.setStyleSheet("\n"
"QPushButton {\n"
"background: #0085ca;\n"
"font-size: 10pt;\n"
"color:white;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"font-size: 10pt;\n"
"border-radius: 10px\n"
"\n"
"}")
        self.generate_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.generate_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.generate_frame.setLineWidth(2)
        self.generate_frame.setObjectName("generate_frame")
        self.generate_document_button = QtWidgets.QPushButton(self.generate_frame)
        self.generate_document_button.setGeometry(QtCore.QRect(40, 540, 146, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.generate_document_button.setFont(font)
        self.generate_document_button.setAutoFillBackground(False)
        self.generate_document_button.setStyleSheet("")
        self.generate_document_button.setIconSize(QtCore.QSize(50, 50))
        self.generate_document_button.setObjectName("generate_document_button")
        self.generated_document_path = QtWidgets.QLineEdit(self.generate_frame)
        self.generated_document_path.setGeometry(QtCore.QRect(160, 600, 411, 31))
        self.generated_document_path.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.generated_document_path.setStyleSheet("background:#757e8a;\n"
"color:black;\n"
"border-radius: 10px")
        self.generated_document_path.setFrame(False)
        self.generated_document_path.setReadOnly(True)
        self.generated_document_path.setObjectName("generated_document_path")
        self.generated_document_sel_location = QtWidgets.QPushButton(self.generate_frame)
        self.generated_document_sel_location.setGeometry(QtCore.QRect(40, 600, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.generated_document_sel_location.setFont(font)
        self.generated_document_sel_location.setStyleSheet("")
        self.generated_document_sel_location.setObjectName("generated_document_sel_location")
        self.update_document_path = QtWidgets.QLineEdit(self.generate_frame)
        self.update_document_path.setGeometry(QtCore.QRect(160, 750, 411, 31))
        self.update_document_path.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.update_document_path.setStyleSheet("background:#757e8a;\n"
"color:black;\n"
"border-radius: 10px")
        self.update_document_path.setFrame(False)
        self.update_document_path.setReadOnly(True)
        self.update_document_path.setObjectName("update_document_path")
        self.update_document_sel_location = QtWidgets.QPushButton(self.generate_frame)
        self.update_document_sel_location.setGeometry(QtCore.QRect(40, 750, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.update_document_sel_location.setFont(font)
        self.update_document_sel_location.setStyleSheet("")
        self.update_document_sel_location.setObjectName("update_document_sel_location")
        self.update_document_button = QtWidgets.QPushButton(self.generate_frame)
        self.update_document_button.setGeometry(QtCore.QRect(40, 690, 146, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update_document_button.setFont(font)
        self.update_document_button.setAutoFillBackground(False)
        self.update_document_button.setStyleSheet("")
        self.update_document_button.setIconSize(QtCore.QSize(50, 50))
        self.update_document_button.setObjectName("update_document_button")
        self.images_preview_text = QtWidgets.QLabel(self.generate_frame)
        self.images_preview_text.setGeometry(QtCore.QRect(210, 20, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.images_preview_text.setFont(font)
        self.images_preview_text.setStyleSheet("color: white;\n"
"text-size: 20px;")
        self.images_preview_text.setAlignment(QtCore.Qt.AlignCenter)
        self.images_preview_text.setObjectName("images_preview_text")
        self.file_view = QtWidgets.QLabel(self.generate_frame)
        self.file_view.setGeometry(QtCore.QRect(20, 90, 571, 361))
        self.file_view.setStyleSheet("background: #1a1a1e;\n"
"border: 1px solid #7a7a81;\n"
"border-radius: 10px")
        self.file_view.setText("")
        self.file_view.setObjectName("file_view")
        self.export_to_document_text = QtWidgets.QLabel(self.generate_frame)
        self.export_to_document_text.setGeometry(QtCore.QRect(10, 445, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.export_to_document_text.setFont(font)
        self.export_to_document_text.setStyleSheet("color: white;\n"
"text-size: 20px;")
        self.export_to_document_text.setLineWidth(0)
        self.export_to_document_text.setAlignment(QtCore.Qt.AlignCenter)
        self.export_to_document_text.setObjectName("export_to_document_text")
        self.line_7 = QtWidgets.QFrame(self.generate_frame)
        self.line_7.setGeometry(QtCore.QRect(15, 475, 186, 11))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.generate_frame)
        self.line_8.setGeometry(QtCore.QRect(410, 475, 186, 11))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_13 = QtWidgets.QFrame(self.generate_frame)
        self.line_13.setGeometry(QtCore.QRect(20, 50, 181, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.generate_frame)
        self.line_14.setGeometry(QtCore.QRect(420, 50, 181, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.export_to_document_text.raise_()
        self.generate_document_button.raise_()
        self.generated_document_path.raise_()
        self.generated_document_sel_location.raise_()
        self.update_document_path.raise_()
        self.update_document_sel_location.raise_()
        self.update_document_button.raise_()
        self.images_preview_text.raise_()
        self.file_view.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.headerr = QtWidgets.QFrame(self.main_body)
        self.headerr.setGeometry(QtCore.QRect(0, 0, 1921, 61))
        self.headerr.setStyleSheet("")
        self.headerr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerr.setObjectName("headerr")
        self.data_exporter = QtWidgets.QLabel(self.headerr)
        self.data_exporter.setGeometry(QtCore.QRect(90, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.data_exporter.setFont(font)
        self.data_exporter.setStyleSheet("color:white;\n"
"")
        self.data_exporter.setObjectName("data_exporter")
        self.minimize_button = QtWidgets.QPushButton(self.headerr)
        self.minimize_button.setGeometry(QtCore.QRect(1790, 0, 41, 61))
        self.minimize_button.setMouseTracking(True)
        self.minimize_button.setStyleSheet("QPushButton {\n"
"background: #121214;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"\n"
"}")
        self.minimize_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon)
        self.minimize_button.setIconSize(QtCore.QSize(20, 20))
        self.minimize_button.setFlat(False)
        self.minimize_button.setObjectName("minimize_button")
        self.exit_button = QtWidgets.QPushButton(self.headerr)
        self.exit_button.setGeometry(QtCore.QRect(1870, 0, 51, 61))
        self.exit_button.setMouseTracking(True)
        self.exit_button.setStyleSheet("QPushButton {\n"
"background: #121214;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"\n"
"}")
        self.exit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon1)
        self.exit_button.setIconSize(QtCore.QSize(25, 25))
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.power_integrations_icon = QtWidgets.QLabel(self.headerr)
        self.power_integrations_icon.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.power_integrations_icon.setText("")
        self.power_integrations_icon.setPixmap(QtGui.QPixmap(":/icons/resources/icons/POWI.D-16de9fb7.png"))
        self.power_integrations_icon.setScaledContents(True)
        self.power_integrations_icon.setObjectName("power_integrations_icon")
        self.maximize_button = QtWidgets.QPushButton(self.headerr)
        self.maximize_button.setGeometry(QtCore.QRect(1830, 0, 41, 61))
        self.maximize_button.setMouseTracking(True)
        self.maximize_button.setStyleSheet("QPushButton {\n"
"background: #121214;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"\n"
"}")
        self.maximize_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/icons/maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximize_button.setIcon(icon2)
        self.maximize_button.setIconSize(QtCore.QSize(20, 20))
        self.maximize_button.setFlat(False)
        self.maximize_button.setObjectName("maximize_button")
        self.data_exporter.raise_()
        self.exit_button.raise_()
        self.power_integrations_icon.raise_()
        self.maximize_button.raise_()
        self.minimize_button.raise_()
        self.selectionframe = QtWidgets.QFrame(self.main_body)
        self.selectionframe.setGeometry(QtCore.QRect(40, 130, 581, 841))
        self.selectionframe.setStyleSheet("QPushButton#load_files_button {\n"
"background: #0085ca;\n"
"font-size: 10pt;\n"
"color:white;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QFrame#performancedata_frame {\n"
"background: #2c2c30;\n"
"}\n"
"\n"
"\n"
"QPushButton#load_files_button:hover {\n"
"    background:rgb(60, 100, 159);\n"
"font-size: 10pt;\n"
"border-radius: 10px\n"
"\n"
"}")
        self.selectionframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectionframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectionframe.setObjectName("selectionframe")
        self.performancedata_frame = QtWidgets.QFrame(self.selectionframe)
        self.performancedata_frame.setGeometry(QtCore.QRect(10, 30, 551, 441))
        self.performancedata_frame.setStyleSheet("\n"
"QPushButton {\n"
"background: #0085ca;\n"
"font-size: 10pt;\n"
"color:white;\n"
"border-radius: 10px\n"
"\n"
"}\n"
"\n"
"QPushButtonn:hover {\n"
"    background:rgb(60, 100, 159);\n"
"font-size: 10pt;\n"
"border-radius: 10px\n"
"\n"
"}")
        self.performancedata_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.performancedata_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.performancedata_frame.setObjectName("performancedata_frame")
        self.performancedata_add = QtWidgets.QPushButton(self.performancedata_frame)
        self.performancedata_add.setGeometry(QtCore.QRect(10, 390, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.performancedata_add.setFont(font)
        self.performancedata_add.setStyleSheet("QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"border-radius: 10px\n"
"}")
        self.performancedata_add.setObjectName("performancedata_add")
        self.performancedata_list = QtWidgets.QListWidget(self.performancedata_frame)
        self.performancedata_list.setGeometry(QtCore.QRect(10, 105, 541, 276))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.performancedata_list.setFont(font)
        self.performancedata_list.setStyleSheet("background: #1a1a1e;\n"
"font-size: 16t;\n"
"color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #7a7a81;")
        self.performancedata_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.performancedata_list.setMidLineWidth(0)
        self.performancedata_list.setDragEnabled(True)
        self.performancedata_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.performancedata_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.performancedata_list.setAlternatingRowColors(False)
        self.performancedata_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.performancedata_list.setUniformItemSizes(True)
        self.performancedata_list.setObjectName("performancedata_list")
        self.performancedata_delete = QtWidgets.QPushButton(self.performancedata_frame)
        self.performancedata_delete.setGeometry(QtCore.QRect(420, 390, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.performancedata_delete.setFont(font)
        self.performancedata_delete.setStyleSheet("QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"border-radius: 10px\n"
"}")
        self.performancedata_delete.setObjectName("performancedata_delete")
        self.performancedata_path = QtWidgets.QLineEdit(self.performancedata_frame)
        self.performancedata_path.setGeometry(QtCore.QRect(130, 65, 421, 31))
        self.performancedata_path.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.performancedata_path.setStyleSheet("background:#757e8a;\n"
"color:black;\n"
"border-radius: 10px")
        self.performancedata_path.setFrame(False)
        self.performancedata_path.setReadOnly(True)
        self.performancedata_path.setObjectName("performancedata_path")
        self.performancedata_sel = QtWidgets.QPushButton(self.performancedata_frame)
        self.performancedata_sel.setGeometry(QtCore.QRect(15, 65, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.performancedata_sel.setFont(font)
        self.performancedata_sel.setStyleSheet("QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"\n"
"border-radius: 10px\n"
"}")
        self.performancedata_sel.setObjectName("performancedata_sel")
        self.line_10 = QtWidgets.QFrame(self.performancedata_frame)
        self.line_10.setGeometry(QtCore.QRect(10, 15, 171, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.performancedata_list_test_2 = QtWidgets.QLabel(self.performancedata_frame)
        self.performancedata_list_test_2.setGeometry(QtCore.QRect(195, -10, 176, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.performancedata_list_test_2.setFont(font)
        self.performancedata_list_test_2.setStyleSheet("color:white;")
        self.performancedata_list_test_2.setObjectName("performancedata_list_test_2")
        self.line_9 = QtWidgets.QFrame(self.performancedata_frame)
        self.line_9.setGeometry(QtCore.QRect(375, 15, 181, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.available_data_list_performance = QtWidgets.QListWidget(self.selectionframe)
        self.available_data_list_performance.setGeometry(QtCore.QRect(20, 470, 541, 341))
        self.available_data_list_performance.setStyleSheet("background: #1a1a1e;\n"
"font-size: 16t;\n"
"color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #7a7a81;")
        self.available_data_list_performance.setDragEnabled(True)
        self.available_data_list_performance.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.available_data_list_performance.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.available_data_list_performance.setAlternatingRowColors(False)
        self.available_data_list_performance.setObjectName("available_data_list_performance")
        self.load_files_button = QtWidgets.QPushButton(self.main_body)
        self.load_files_button.setGeometry(QtCore.QRect(40, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.load_files_button.setFont(font)
        self.load_files_button.setMouseTracking(True)
        self.load_files_button.setStyleSheet("")
        self.load_files_button.setObjectName("load_files_button")
        self.refresh_button = QtWidgets.QPushButton(self.main_body)
        self.refresh_button.setGeometry(QtCore.QRect(180, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.refresh_button.setFont(font)
        self.refresh_button.setMouseTracking(True)
        self.refresh_button.setStyleSheet("")
        self.refresh_button.setObjectName("refresh_button")
        self.available_data_frame = QtWidgets.QFrame(self.main_body)
        self.available_data_frame.setGeometry(QtCore.QRect(660, 130, 581, 841))
        self.available_data_frame.setStyleSheet("QPushButton {\n"
"background: #0085ca;\n"
"font-size: 10pt;\n"
"color:white;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"font-size: 10pt;\n"
"border-radius: 10px\n"
"\n"
"}")
        self.available_data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.available_data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.available_data_frame.setObjectName("available_data_frame")
        self.waveforms_frame = QtWidgets.QFrame(self.available_data_frame)
        self.waveforms_frame.setGeometry(QtCore.QRect(0, 90, 576, 366))
        self.waveforms_frame.setStyleSheet("QPushButton {\n"
"background: #0085ca;\n"
"font-size: 10pt;\n"
"color:white;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(60, 100, 159);\n"
"font-size: 10pt;\n"
"border-radius: 10px\n"
"}")
        self.waveforms_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.waveforms_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.waveforms_frame.setObjectName("waveforms_frame")
        self.waveforms_add = QtWidgets.QPushButton(self.waveforms_frame)
        self.waveforms_add.setGeometry(QtCore.QRect(20, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.waveforms_add.setFont(font)
        self.waveforms_add.setStyleSheet("")
        self.waveforms_add.setObjectName("waveforms_add")
        self.waveforms_list = QtWidgets.QListWidget(self.waveforms_frame)
        self.waveforms_list.setGeometry(QtCore.QRect(20, 45, 541, 276))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        self.waveforms_list.setFont(font)
        self.waveforms_list.setStyleSheet("background: #1a1a1e;\n"
"font-size: 16t;\n"
"color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #7a7a81;")
        self.waveforms_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.waveforms_list.setMidLineWidth(0)
        self.waveforms_list.setDragEnabled(True)
        self.waveforms_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.waveforms_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.waveforms_list.setAlternatingRowColors(False)
        self.waveforms_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.waveforms_list.setUniformItemSizes(True)
        self.waveforms_list.setObjectName("waveforms_list")
        self.waveforms_delete = QtWidgets.QPushButton(self.waveforms_frame)
        self.waveforms_delete.setGeometry(QtCore.QRect(430, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.waveforms_delete.setFont(font)
        self.waveforms_delete.setStyleSheet("")
        self.waveforms_delete.setObjectName("waveforms_delete")
        self.waveforms_sel = QtWidgets.QPushButton(self.waveforms_frame)
        self.waveforms_sel.setGeometry(QtCore.QRect(20, 5, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.waveforms_sel.setFont(font)
        self.waveforms_sel.setStyleSheet("")
        self.waveforms_sel.setObjectName("waveforms_sel")
        self.waveforms_path = QtWidgets.QLineEdit(self.waveforms_frame)
        self.waveforms_path.setGeometry(QtCore.QRect(135, 5, 426, 31))
        self.waveforms_path.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.waveforms_path.setStyleSheet("background:#757e8a;\n"
"color:black;\n"
"border-radius: 10px")
        self.waveforms_path.setFrame(False)
        self.waveforms_path.setReadOnly(True)
        self.waveforms_path.setObjectName("waveforms_path")
        self.waveforms_list_text_2 = QtWidgets.QLabel(self.available_data_frame)
        self.waveforms_list_text_2.setGeometry(QtCore.QRect(235, 25, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.waveforms_list_text_2.setFont(font)
        self.waveforms_list_text_2.setStyleSheet("color:white;")
        self.waveforms_list_text_2.setObjectName("waveforms_list_text_2")
        self.line_11 = QtWidgets.QFrame(self.available_data_frame)
        self.line_11.setGeometry(QtCore.QRect(10, 50, 211, 11))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.available_data_frame)
        self.line_12.setGeometry(QtCore.QRect(350, 50, 221, 11))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.available_data_list__waveforms = QtWidgets.QListWidget(self.available_data_frame)
        self.available_data_list__waveforms.setGeometry(QtCore.QRect(20, 470, 541, 341))
        self.available_data_list__waveforms.setStyleSheet("background: #1a1a1e;\n"
"font-size: 16t;\n"
"color: white;\n"
"border-radius: 10px;\n"
"border: 1px solid #7a7a81;")
        self.available_data_list__waveforms.setDragEnabled(True)
        self.available_data_list__waveforms.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.available_data_list__waveforms.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.available_data_list__waveforms.setAlternatingRowColors(False)
        self.available_data_list__waveforms.setObjectName("available_data_list__waveforms")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.performancedata_list.setCurrentRow(-1)
        self.waveforms_list.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.waveforms_text_2.setText(_translate("MainWindow", "July 2025"))
        self.waveforms_text_3.setText(_translate("MainWindow", "© CRB"))
        self.generate_document_button.setText(_translate("MainWindow", "Generate Document"))
        self.generated_document_sel_location.setText(_translate("MainWindow", "Output Folder:"))
        self.update_document_sel_location.setText(_translate("MainWindow", "Select File:"))
        self.update_document_button.setText(_translate("MainWindow", "Update Document"))
        self.images_preview_text.setText(_translate("MainWindow", "Waveforms Preview"))
        self.export_to_document_text.setText(_translate("MainWindow", "Export to Document"))
        self.data_exporter.setText(_translate("MainWindow", "AUTOMATED DATA EXPORTER"))
        self.performancedata_add.setText(_translate("MainWindow", "Add Data"))
        self.performancedata_list.setSortingEnabled(False)
        self.performancedata_delete.setText(_translate("MainWindow", "Delete Data"))
        self.performancedata_sel.setText(_translate("MainWindow", "Select Folder:"))
        self.performancedata_list_test_2.setText(_translate("MainWindow", "Performance Data"))
        self.available_data_list_performance.setSortingEnabled(False)
        self.load_files_button.setText(_translate("MainWindow", "Load Tests"))
        self.refresh_button.setText(_translate("MainWindow", "Refresh Items"))
        self.waveforms_add.setText(_translate("MainWindow", "Add Data"))
        self.waveforms_list.setSortingEnabled(False)
        self.waveforms_delete.setText(_translate("MainWindow", "Delete Data"))
        self.waveforms_sel.setText(_translate("MainWindow", "Select Folder:"))
        self.waveforms_list_text_2.setText(_translate("MainWindow", "Waveforms"))
        self.available_data_list__waveforms.setSortingEnabled(False)
import resource_rc
